import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const forwardedHost = headersList.get("x-forwarded-host") || "";
  const host = headersList.get("host") || "";

  // Header x-url chứa full path hiện hành trên Next.js 14+ / 15
  const currentUrl = headersList.get("x-url") || headersList.get("referer") || "";
  const isAdvisorFlow = forwardedHost === "advisor.finpeace.cloud" || host === "advisor.finpeace.cloud";

  // Server-Side Redirect tuyệt đối cho Subdomain về /advisor. Xoá ma trận Middleware mông lung.
  if (isAdvisorFlow && !currentUrl.includes("/advisor")) {
    redirect("/advisor");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
